import type { LabelPreset } from "./types";

export const CUSTOM_PRESET_ID = "custom";

const a4 = {
  pageWidthMm: 210,
  pageHeightMm: 297,
  innerPaddingMm: 0.2,
  qrScale: 0.9,
  textGapMm: 0.25,
  minTextSizeMm: 1.2,
  maxTextSizeMm: 3.3,
};

export const PRESET_LIBRARY: LabelPreset[] = [
  {
    ...a4,
    id: "averyL4731",
    name: "L4731",
    manufacturer: "Avery Zweckform",
    status: "verified",
    source: "Avery L4731 / reference values from existing Paperless ASN tools",
    columns: 7,
    rows: 27,
    labelWidthMm: 25.4,
    labelHeightMm: 10,
    gutterXMm: 2.5,
    gutterYMm: 0,
    marginLeftMm: 9,
    marginTopMm: 13.5,
  },
  {
    ...a4,
    id: "averyL4732",
    name: "L4732",
    manufacturer: "Avery Zweckform",
    status: "verified",
    source: "Avery L4732 / reference values from existing Paperless ASN tools",
    columns: 5,
    rows: 16,
    labelWidthMm: 35.6,
    labelHeightMm: 16.9,
    gutterXMm: 2.5,
    gutterYMm: 0,
    marginLeftMm: 11,
    marginTopMm: 13.5,
    innerPaddingMm: 0.45,
    qrScale: 0.88,
    textGapMm: 0.45,
    minTextSizeMm: 1.7,
    maxTextSizeMm: 4.2,
  },
  {
    ...a4,
    id: "averyL7162",
    name: "L7162",
    manufacturer: "Avery Zweckform",
    status: "provisional",
    source: "Avery L7162 / reference values from existing Paperless ASN tools",
    columns: 4,
    rows: 16,
    labelWidthMm: 49.5,
    labelHeightMm: 16.9,
    gutterXMm: 2.5,
    gutterYMm: 0,
    marginLeftMm: 11,
    marginTopMm: 13.5,
  },
  {
    id: "avery3657",
    name: "3657",
    manufacturer: "Avery",
    status: "provisional",
    source: "Avery 3657 / reference values from existing Paperless ASN tools",
    columns: 4,
    rows: 10,
    labelWidthMm: 48.5,
    labelHeightMm: 25.4,
    gutterXMm: 0,
    gutterYMm: 0,
    marginLeftMm: 8,
    marginTopMm: 21.75,
    innerPaddingMm: 0.75,
    qrScale: 0.86,
    textGapMm: 0.75,
    minTextSizeMm: 2.1,
    maxTextSizeMm: 5.1,
    pageWidthMm: 210,
    pageHeightMm: 297,
  },
  {
    ...a4,
    id: "herma10003",
    name: "10003",
    manufacturer: "HERMA",
    status: "verified",
    source: "HERMA 10003 / reference values from existing Paperless ASN tools",
    columns: 5,
    rows: 16,
    labelWidthMm: 35.56,
    labelHeightMm: 16.93,
    gutterXMm: 2.54,
    gutterYMm: 0,
    marginLeftMm: 11.02,
    marginTopMm: 13.06,
    innerPaddingMm: 0.45,
    qrScale: 0.88,
    textGapMm: 0.45,
    minTextSizeMm: 1.7,
    maxTextSizeMm: 4.2,
  },
  {
    ...a4,
    id: "herma4201",
    name: "4201",
    manufacturer: "HERMA",
    status: "provisional",
    source: "HERMA 4201 / reference values from existing Paperless ASN tools",
    columns: 4,
    rows: 16,
    labelWidthMm: 45.7,
    labelHeightMm: 16.9,
    gutterXMm: 2.5,
    gutterYMm: 0,
    marginLeftMm: 8,
    marginTopMm: 13,
  },
  {
    id: "herma4346",
    name: "4346",
    manufacturer: "HERMA",
    status: "verified",
    source: "HERMA 4346 / reference values from existing Paperless ASN tools",
    columns: 4,
    rows: 12,
    labelWidthMm: 45.72,
    labelHeightMm: 21.167,
    gutterXMm: 2.54,
    gutterYMm: 0,
    marginLeftMm: 9.75,
    marginTopMm: 21.5,
    innerPaddingMm: 0.65,
    qrScale: 0.88,
    textGapMm: 0.65,
    minTextSizeMm: 2,
    maxTextSizeMm: 4.8,
    pageWidthMm: 210,
    pageHeightMm: 297,
  },
  {
    ...a4,
    id: "herma4333",
    name: "4333",
    manufacturer: "HERMA",
    status: "provisional",
    source: "HERMA 4333 / reference values from existing Paperless ASN tools",
    columns: 7,
    rows: 27,
    labelWidthMm: 25.4,
    labelHeightMm: 10,
    gutterXMm: 2.54,
    gutterYMm: 0,
    marginLeftMm: 8.48,
    marginTopMm: 13.5,
  },
  {
    id: "genericA4Cut",
    name: "Generic A4 Cut",
    manufacturer: "Generic",
    status: "provisional",
    source: "Generic manual-cut A4 fallback",
    columns: 5,
    rows: 14,
    labelWidthMm: 40,
    labelHeightMm: 20,
    gutterXMm: 0,
    gutterYMm: 0,
    marginLeftMm: 5,
    marginTopMm: 4,
    innerPaddingMm: 0.6,
    qrScale: 0.88,
    textGapMm: 0.6,
    minTextSizeMm: 2,
    maxTextSizeMm: 5,
    pageWidthMm: 210,
    pageHeightMm: 297,
  },
];

export function createDefaultCustomPreset(): LabelPreset {
  return {
    id: CUSTOM_PRESET_ID,
    name: "Custom A4",
    manufacturer: "Custom",
    status: "provisional",
    source: "User-defined geometry",
    columns: 5,
    rows: 16,
    labelWidthMm: 35.6,
    labelHeightMm: 16.9,
    gutterXMm: 2.5,
    gutterYMm: 0,
    marginLeftMm: 11,
    marginTopMm: 13.5,
    pageWidthMm: 210,
    pageHeightMm: 297,
    innerPaddingMm: 0.45,
    qrScale: 0.88,
    textGapMm: 0.45,
    minTextSizeMm: 1.7,
    maxTextSizeMm: 4.2,
    isCustom: true,
  };
}

export function getPresetById(
  presetId: string,
  customPreset?: LabelPreset,
): LabelPreset {
  if (presetId === CUSTOM_PRESET_ID) {
    return customPreset ?? createDefaultCustomPreset();
  }

  return (
    PRESET_LIBRARY.find((preset) => preset.id === presetId) ?? PRESET_LIBRARY[0]
  );
}
